### ISSUE TITLE
v3.2.1 not working with multiple versions of atom

### ISSUE THREAD

**Issue by fcooper8472** [AtomLinter/linter-proselint#54] opened 2017-08-28 16:30 UTC
`linter-proselint v3.2.1` fails to start on `Ubuntu 16.04` with `atom 1.12.7` and `1.19.3`, with the following error:

```
linter-registry.js [sm]:137 [Linter] Error running proselint SyntaxError: Unexpected token C in JSON at position 0
    at JSON.parse (<anonymous>)
    at index.js [sm]:30
(anonymous) @ linter-registry.js [sm]:137
linter-registry.js [sm]:137 [Linter] Error running proselint SyntaxError: Unexpected token C in JSON at position 0
    at JSON.parse (<anonymous>)
    at index.js [sm]:30
(anonymous) @ linter-registry.js [sm]:137
linter-registry.js [sm]:137 [Linter] Error running proselint Error: Process execution timed out
    at /home/fergus/.atom/packages/linter/node_modules/sb-exec/lib/index.js:92
(anonymous) @ linter-registry.js [sm]:137
```

The `proselint` version installed is `0.8.0`.

**Comment by Arcanemagus** [comment] 2017-08-28 18:24
Duplicate of #44

**Comment by Arcanemagus** [comment] 2017-08-28 18:25
Looks like it hasn't been working for a while...

**Closed by Arcanemagus** 2017-08-28 18:24 UTC
